services:
  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    network_mode: "host"
    # --- ADD THIS SECTION ---
    security_opt:
      - apparmor:unconfined
    # ------------------------
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    volumes:
      - "../config.yaml:/home/node/app/config.yaml"
      - "../data:/home/node/app/data"
      - "../plugins:/home/node/app/plugins"
      - "../public:/home/node/app/public"
      - "../extensions:/home/node/app/public/scripts/extensions/third-party"
    restart: unless-stopped
